services:
  server:
    container_name: z38_server
    build: ./server/
    image: z38_udp_server:latest
    ports:
      - "8888:8888"
    networks:
      z38_network:
        aliases:
          - z38_server

  client:
    container_name: z38_client
    build: ./client/
    image: z38_udp_client:latest
    tty: true
    cap_add:
        - NET_ADMIN
    networks:
      - z38_network
    command: z38_server

networks:
  z38_network:
    external: true
