version: '3.8'

services:
  server:
    container_name: z38_server
    build: ./server/
    image: z38_tcp_server:latest
    ports:
      - "8888:8888" 
    networks:
      - z38_network

  client:
    container_name: z38_client
    build: ./client/
    image: z38_tcp_client:latest
    tty: true 
    networks:
      - z38_network
    command: z38_server 

networks:
  z38_network:
    external: true